name: my_store
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  flutter_swiper : ^1.1.6
  carousel_slider: ^1.3.0
  badges: ^1.1.0
  http: ^0.12.0+2
  font_awesome_flutter: ^8.5.0
  fluttertoast: ^3.1.3
  custom_radio: ^0.1.2
  flutter_rating_bar: ^3.0.0
  page_transition: "^1.1.5"
  flutter_spinkit: ^3.1.0
  fancy_on_boarding: ^1.6.0
  shared_preferences: ^0.5.8
  provider: ^2.0.1
  bubble_bottom_bar: ^1.2.0
  flutter_slidable: "^0.5.4"
  shimmer: ^1.1.1
  simple_animations: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/languages/
   - assets/category/
   - assets/deal_of_the_day/
   - assets/home_slider/
   - assets/json/
   - assets/products/
   - assets/logo.png
   - assets/user_profile/
   - assets/country_flag/
   - assets/category_grid/
   - assets/payment_icon/
   - assets/onboarding/

  fonts:
    - family: Francois One
      fonts:
        - asset: fonts/FrancoisOne-Regular.ttf
          weight: 400
    - family: Alatsi
      fonts:
        - asset: fonts/Alatsi-Regular.ttf
          weight: 400
    - family: Kaushan Script
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf
          weight: 400
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
          weight: 400
    - family: Jost
      fonts:
        - asset: fonts/Jost-VariableFont_wght.ttf
          weight: 400
    - family: Signika Negative
      fonts:
        - asset: fonts/signika_negative/SignikaNegative-Regular.ttf
        - asset: fonts/signika_negative/SignikaNegative-Bold.ttf
          weight: 700